# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Botway < Formula
  desc "🤖 Generate, build, handle and deploy your own bot with your favorite language, for Discord, or Telegram, or Slack"
  homepage "https://github.com/abdfnx/botway"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/abdfnx/botway/releases/download/v0.1.3/botway_macos_v0.1.3_arm64.zip"
      sha256 "799d7e31a98f1eab1f86285f45982a40cb521e169e5fab1e75cb1bf642e9a14d"

      def install
        bin.install "bin/botway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/botway/releases/download/v0.1.3/botway_macos_v0.1.3_amd64.zip"
      sha256 "f539a4a28e9ebfddcb6fa37c87fbe82848315a8b20e54cddbbcdfe0be989a5cb"

      def install
        bin.install "bin/botway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/botway/releases/download/v0.1.3/botway_linux_v0.1.3_arm.zip"
      sha256 "878210638b4d3c38a17f03f752ba80a5cbdd0251b094692e674a3905217ccad0"

      def install
        bin.install "bin/botway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/botway/releases/download/v0.1.3/botway_linux_v0.1.3_arm64.zip"
      sha256 "4172302369aafaf8e499c6b92b466aa08525422cca480661dcd3f9c67345e905"

      def install
        bin.install "bin/botway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/botway/releases/download/v0.1.3/botway_linux_v0.1.3_amd64.zip"
      sha256 "573a2c4a1b16f288b16a7ad28c68540c656f44809539039685eaa4ba872bd564"

      def install
        bin.install "bin/botway"
      end
    end
  end
end
