# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Botway < Formula
  desc "🤖 Generate, build, handle and deploy your own bot with your favorite language, for Discord, or Telegram, or Slack"
  homepage "https://github.com/abdfnx/botway"
  version "0.1.0-beta.521"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/abdfnx/botway/releases/download/v0.1.0-beta.521/botway_macos_v0.1.0-beta.521_arm64.zip"
      sha256 "ea66848e953276352cfc42c4725044c7aafa2eb654503cd3dd1163790678d464"

      def install
        bin.install "bin/botway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/botway/releases/download/v0.1.0-beta.521/botway_macos_v0.1.0-beta.521_amd64.zip"
      sha256 "1199a04511bdf7e9d74d1a96e40163ba5568a8a02c5bebf8e4adadb515be78d7"

      def install
        bin.install "bin/botway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/botway/releases/download/v0.1.0-beta.521/botway_linux_v0.1.0-beta.521_arm.zip"
      sha256 "06aa30a9b70e8d3922832003b2c58fb364bda0c044a0bacf15c88535c0ba8d94"

      def install
        bin.install "bin/botway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/botway/releases/download/v0.1.0-beta.521/botway_linux_v0.1.0-beta.521_arm64.zip"
      sha256 "292398279c08fcd2b32f0f9348bdb3d49dadb09ffae399cbf3c6ccfdbbd94ca1"

      def install
        bin.install "bin/botway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/botway/releases/download/v0.1.0-beta.521/botway_linux_v0.1.0-beta.521_amd64.zip"
      sha256 "3db976e116b8427c859abaeed9e431fd5299675159b3ed989367de4296808122"

      def install
        bin.install "bin/botway"
      end
    end
  end
end
