# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Botway < Formula
  desc "🤖 Generate, build, handle and deploy your own bot with your favorite language, for Discord, or Telegram, or Slack"
  homepage "https://github.com/abdfnx/botway"
  version "0.1.83"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/abdfnx/botway/releases/download/v0.1.83/botway_macos_v0.1.83_arm64.zip"
      sha256 "bf080baaaf7e2cc763a62d8a6c11610ed7dbbbf97f98ba8767b6dda638e06d9c"

      def install
        bin.install "bin/botway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/botway/releases/download/v0.1.83/botway_macos_v0.1.83_amd64.zip"
      sha256 "dacac5171d7c683d68ddf83a577735215beeada7883e073b9fe0d0197db2fdc5"

      def install
        bin.install "bin/botway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/botway/releases/download/v0.1.83/botway_linux_v0.1.83_arm64.zip"
      sha256 "bc71e952ca45d6f22d76bec2104ca5246f432c1d070b051064f40c5231020943"

      def install
        bin.install "bin/botway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/botway/releases/download/v0.1.83/botway_linux_v0.1.83_amd64.zip"
      sha256 "78fb4e00a5c73139111ba0c01d08b7453790664ffcf3239eaea989331e2071d1"

      def install
        bin.install "bin/botway"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/botway/releases/download/v0.1.83/botway_linux_v0.1.83_arm.zip"
      sha256 "f283a6ecf21d019bb2ea1d210a88310490821553b42409fbc449b56d68bfb2ac"

      def install
        bin.install "bin/botway"
      end
    end
  end
end
