# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doko < Formula
  desc "🐳 docker you know but with TUI."
  homepage "https://github.com/abdfnx/doko"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/doko/releases/download/v0.1.2/doko_macos_v0.1.2_amd64.zip"
      sha256 "7f586087c7f1f20bba658bcca22488e594afa31850aa8ffdd4d1baeafa42cb55"

      def install
        bin.install "bin/doko"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdfnx/doko/releases/download/v0.1.2/doko_macos_v0.1.2_arm64.zip"
      sha256 "bece2e81cf5e687a0819c0d75c796c6516fd22e84092566664e09ea404a0edcf"

      def install
        bin.install "bin/doko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/doko/releases/download/v0.1.2/doko_linux_v0.1.2_arm.zip"
      sha256 "800b23e47e3d885e260f9d25508592cb412d65b0adfc5eaa7e26da719a2d7f2c"

      def install
        bin.install "bin/doko"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/doko/releases/download/v0.1.2/doko_linux_v0.1.2_arm64.zip"
      sha256 "d86c62b3e0589a3f84cf69ac7a8524b9c4d215be127399d5ff768ce4b6709055"

      def install
        bin.install "bin/doko"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/doko/releases/download/v0.1.2/doko_linux_v0.1.2_amd64.zip"
      sha256 "0028190d783eb90bee5852b441b413cd2279fd73768036ca471b628c68d99813"

      def install
        bin.install "bin/doko"
      end
    end
  end
end
