# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doko < Formula
  desc "🐳 docker you know but with console user interface."
  homepage "https://github.com/abdfnx/doko"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/abdfnx/doko/releases/download/v0.1.0/doko_macos_v0.1.0_arm64.zip"
      sha256 "6ff14887e513a0521ef8d0189cb432327c46ffbe0a4455ec22c2447068a4162d"

      def install
        bin.install "bin/doko"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/doko/releases/download/v0.1.0/doko_macos_v0.1.0_amd64.zip"
      sha256 "332ff512c566ad3fd41e263e9f64bf31bc18682fec137833ab7b59a322f0beb2"

      def install
        bin.install "bin/doko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/doko/releases/download/v0.1.0/doko_linux_v0.1.0_amd64.zip"
      sha256 "609b1b4a89f39c6280e7440209c31c1f6c67dbf7716e8b4451b56989726f97c1"

      def install
        bin.install "bin/doko"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/doko/releases/download/v0.1.0/doko_linux_v0.1.0_arm64.zip"
      sha256 "9b46ef28491a9bb291da8a1612f6d268cc6efdd389ee98038be3c1636d9e7b93"

      def install
        bin.install "bin/doko"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/doko/releases/download/v0.1.0/doko_linux_v0.1.0_arm.zip"
      sha256 "193c32c557cb27d2bb722152bd9ccc8a911524abe92a8b5c429ea674b515dbbc"

      def install
        bin.install "bin/doko"
      end
    end
  end
end
