# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomo < Formula
  desc "📐 Simple Golang multi modules tool"
  homepage "https://github.com/abdfnx/gomo"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/abdfnx/gomo/releases/download/v0.0.2/gomo_macos_v0.0.2_arm64.zip"
      sha256 "569c062110f0acbab30ee0b675b221a9433b0b2951cebf9b1cf83bdaa4761b20"

      def install
        bin.install "bin/gomo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/gomo/releases/download/v0.0.2/gomo_macos_v0.0.2_amd64.zip"
      sha256 "1478d366907503f680ce53b202ec05cf9b5409fc65770e0fec468f403b764b2c"

      def install
        bin.install "bin/gomo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/gomo/releases/download/v0.0.2/gomo_linux_v0.0.2_amd64.zip"
      sha256 "6b8fb5d0a67308776ce35d328fbeff9640900d994bf5a82e06a40e36261d6c41"

      def install
        bin.install "bin/gomo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/gomo/releases/download/v0.0.2/gomo_linux_v0.0.2_arm64.zip"
      sha256 "9ee8a7074e39babc3be1646636ea16e516fc964c10cc8c8a072ddead946ea5c1"

      def install
        bin.install "bin/gomo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/gomo/releases/download/v0.0.2/gomo_linux_v0.0.2_arm.zip"
      sha256 "39aad53d286ed32eedcfd781233169119166fd622f8afde24ec0e6cadb97d07b"

      def install
        bin.install "bin/gomo"
      end
    end
  end
end
