# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomo < Formula
  desc "📐 Simple Golang multi modules tool"
  homepage "https://github.com/abdfnx/gomo"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/abdfnx/gomo/releases/download/v0.0.1/gomo_macos_v0.0.1_arm64.zip"
      sha256 "9ca9c1cce6bd2fe94a3d5ff28bd7e3be65b20cf5cb2d0bb016e8ff6c8cbb3e3f"

      def install
        bin.install "bin/gomo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/gomo/releases/download/v0.0.1/gomo_macos_v0.0.1_amd64.zip"
      sha256 "e4ad993dda947c44b0d40fe9a6b70d666bdb7f2b9cd5ec2ee2b257507502f25b"

      def install
        bin.install "bin/gomo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/gomo/releases/download/v0.0.1/gomo_linux_v0.0.1_arm64.zip"
      sha256 "5e642cf89e14d835b22aeacb321a1145bdbfd48a3bd370de1790a115dcaaef7b"

      def install
        bin.install "bin/gomo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/gomo/releases/download/v0.0.1/gomo_linux_v0.0.1_amd64.zip"
      sha256 "fa46d98df1478efd86c512f16b0a11ad7f7c7e4053bf6141c84eb174c88c49f5"

      def install
        bin.install "bin/gomo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/gomo/releases/download/v0.0.1/gomo_linux_v0.0.1_arm.zip"
      sha256 "8020b05b89e8c8c4e9a9b55fc214782e820c68fd6650fd41babca83e31850151"

      def install
        bin.install "bin/gomo"
      end
    end
  end
end
