# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Instal < Formula
  desc "🛰️ Install any binary app from a script URL."
  homepage "https://github.com/abdfnx/instal"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/instal/releases/download/v0.1.0/instal_macos_v0.1.0_amd64.zip"
      sha256 "7538319a3624250dae162f5c7d4492c6826a84b2deed6f7bf2bec489bde40b14"

      def install
        bin.install "bin/instal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdfnx/instal/releases/download/v0.1.0/instal_macos_v0.1.0_arm64.zip"
      sha256 "5dacac74be6e5f36c72349a2e5454d55cf700dd91caa3dd5f93ce7128e23447e"

      def install
        bin.install "bin/instal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/instal/releases/download/v0.1.0/instal_linux_v0.1.0_arm64.zip"
      sha256 "59f125d61fa13d5feb1037b5cda19641fb6e98bb15c2972da49e57b7dcd7b2aa"

      def install
        bin.install "bin/instal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/instal/releases/download/v0.1.0/instal_linux_v0.1.0_amd64.zip"
      sha256 "d8249e4fb5fdc4bf60d45ca4712e6a233f6eeef6c7ba22208bbef5841dbb28ce"

      def install
        bin.install "bin/instal"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/instal/releases/download/v0.1.0/instal_linux_v0.1.0_arm.zip"
      sha256 "dc22b5ff0d389856cb8a7d4ce8332d51ecdb8bb0f9e54946c537cc7cc6c39a94"

      def install
        bin.install "bin/instal"
      end
    end
  end
end
