# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Instal < Formula
  desc "🛰️ Install any binary app from a script URL."
  homepage "https://github.com/abdfnx/instal"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/instal/releases/download/v0.1.0/instal_macos_v0.1.0_amd64.zip"
      sha256 "5cc0048a3f9a2729d074e173d7b10a922822be3e631e38f17c4e7f1026648eb5"

      def install
        bin.install "bin/instal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdfnx/instal/releases/download/v0.1.0/instal_macos_v0.1.0_arm64.zip"
      sha256 "1baa660208c6c41701a2080d3bb3491314f15fd08569a12d2604b422f7890bb2"

      def install
        bin.install "bin/instal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/instal/releases/download/v0.1.0/instal_linux_v0.1.0_arm.zip"
      sha256 "b082a53be95c98ba45ca373593696ca11039125ad99c80ce2f41bb62603b5535"

      def install
        bin.install "bin/instal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/instal/releases/download/v0.1.0/instal_linux_v0.1.0_amd64.zip"
      sha256 "f761f46cf21772a49b97a72f481296928950522d8e93675c64fc16028f9c0be7"

      def install
        bin.install "bin/instal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/instal/releases/download/v0.1.0/instal_linux_v0.1.0_arm64.zip"
      sha256 "fd22698edc5b5f59dbcecbddfe813e76f9dee4a6bd1669c03cba9f64bf0309de"

      def install
        bin.install "bin/instal"
      end
    end
  end
end
