# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Instal < Formula
  desc "🛰️ Install any binary app from a script URL."
  homepage "https://github.com/abdfnx/instal"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/instal/releases/download/v0.1.0/instal_macos_v0.1.0_amd64.zip"
      sha256 "cea17828ca5a3559ecec8d4340de3be5a41b9c2a7e0ae6871bf4f6636a5887af"

      def install
        bin.install "bin/instal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdfnx/instal/releases/download/v0.1.0/instal_macos_v0.1.0_arm64.zip"
      sha256 "5f94218e329a848f35badf2b7016a3220de81bc20ccfb44f5046758e53ebd6ac"

      def install
        bin.install "bin/instal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/instal/releases/download/v0.1.0/instal_linux_v0.1.0_amd64.zip"
      sha256 "f33a8aa940b685c825618ad8c677890802d59730d008d12cfc7be5e3410bc8f6"

      def install
        bin.install "bin/instal"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/instal/releases/download/v0.1.0/instal_linux_v0.1.0_arm.zip"
      sha256 "021393210925bf3dc6c8734282e9cfe365638d880b035fcb785fc8e03fd154ff"

      def install
        bin.install "bin/instal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/instal/releases/download/v0.1.0/instal_linux_v0.1.0_arm64.zip"
      sha256 "653624f3c124de1340a4ef687214463dc6f4758988331cf4a6d08369fa06883b"

      def install
        bin.install "bin/instal"
      end
    end
  end
end
