# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Resto < Formula
  desc "a CLI app can send pretty HTTP & API requests with TUI"
  homepage "https://github.com/abdfnx/resto"
  version "0.1.3-test35"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/abdfnx/resto/releases/download/v0.1.3-test35/resto_macos_v0.1.3-test35_arm64.zip"
      sha256 "b43a2d77413e0ce4853c663a35877263eb43fa219f695d959ad29a6869e90424"

      def install
        bin.install "bin/resto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/resto/releases/download/v0.1.3-test35/resto_macos_v0.1.3-test35_amd64.zip"
      sha256 "d865c85901aaf8b9b66340d57c3d1f8110ce54630226a2b923a192d6ff64de67"

      def install
        bin.install "bin/resto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/resto/releases/download/v0.1.3-test35/resto_linux_v0.1.3-test35_arm.zip"
      sha256 "30b12b26c9c90700c1dea6ec8502d52aaf8cdc5225b3d214bef3e24b4d69c1bd"

      def install
        bin.install "bin/resto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/resto/releases/download/v0.1.3-test35/resto_linux_v0.1.3-test35_amd64.zip"
      sha256 "a2bf9331467ebb3ad03e6ebb7c837eefe237a53ca12c1dbbe48ec0051a750b9b"

      def install
        bin.install "bin/resto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/resto/releases/download/v0.1.3-test35/resto_linux_v0.1.3-test35_arm64.zip"
      sha256 "ad3da1c1605abfe15a7b93b5baab61a4d843309192fb3e6cee4afcfbbb0cd2e5"

      def install
        bin.install "bin/resto"
      end
    end
  end
end
