# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Resto < Formula
  desc "a CLI app can send pretty HTTP & API requests with TUI"
  homepage "https://github.com/abdfnx/resto"
  version "0.1.3-test30"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/resto/releases/download/v0.1.3-test30/resto_macos_v0.1.3-test30_amd64.zip"
      sha256 "7ec182b910311eb04b669fb5ce900154141ee0aabd04f8d42db664758016fb37"

      def install
        bin.install "bin/resto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdfnx/resto/releases/download/v0.1.3-test30/resto_macos_v0.1.3-test30_arm64.zip"
      sha256 "384e2994b40ebfe733bae5796db4314d087cc9e04bf7a9e608ae0b4901b0040d"

      def install
        bin.install "bin/resto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/resto/releases/download/v0.1.3-test30/resto_linux_v0.1.3-test30_arm.zip"
      sha256 "d6c4dfaa99cad2cc40bc112c40877b8cc3a43404e573a9dacfcfdc773b314d29"

      def install
        bin.install "bin/resto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/resto/releases/download/v0.1.3-test30/resto_linux_v0.1.3-test30_arm64.zip"
      sha256 "b61d185bd22ff070f75b15850361c1e9d45d34dfc13cd486f5cdc99d0a90afc8"

      def install
        bin.install "bin/resto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/resto/releases/download/v0.1.3-test30/resto_linux_v0.1.3-test30_amd64.zip"
      sha256 "d4f78641d5526bb26ad134556117d33620522310f57cbf72813f88d63a327dae"

      def install
        bin.install "bin/resto"
      end
    end
  end
end
