# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tran < Formula
  desc "🖥️ Securely transfer and send anything between computers with TUI"
  homepage "https://github.com/abdfnx/tran"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/tran/releases/download/v0.1.0/tran_macos_v0.1.0_amd64.zip"
      sha256 "05facfc6ecd9b83b3ea898e91b35750b11636861b745a8392c9282c71fee332c"

      def install
        bin.install "bin/tran"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdfnx/tran/releases/download/v0.1.0/tran_macos_v0.1.0_arm64.zip"
      sha256 "fcacabf501a429c8efd266427160f9c1ab199f56bb6cf92a837a6953ea359856"

      def install
        bin.install "bin/tran"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/tran/releases/download/v0.1.0/tran_linux_v0.1.0_arm.zip"
      sha256 "5f1a702da8b460a8ee9cf0860f647eaa628385560da4f58d30f6f35d9129ec6d"

      def install
        bin.install "bin/tran"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/tran/releases/download/v0.1.0/tran_linux_v0.1.0_amd64.zip"
      sha256 "94a2d2653e4875b03887fc2378760983061dd8b25d0789e612ed7c2b7cfb91b7"

      def install
        bin.install "bin/tran"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/tran/releases/download/v0.1.0/tran_linux_v0.1.0_arm64.zip"
      sha256 "2c6c1c91b1c4c261c4fd231e20a3396497f0b301906f769c7593fb25e1fda476"

      def install
        bin.install "bin/tran"
      end
    end
  end
end
