# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tran < Formula
  desc "🖥️ Securely transfer and send anything between computers with TUI"
  homepage "https://github.com/abdfnx/tran"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/tran/releases/download/v0.1.0/tran_macos_v0.1.0_amd64.zip"
      sha256 "7ce3ba29220f13af54ed1fd95a3e644a039f7aa188b1c6f2292b00046a890e37"

      def install
        bin.install "bin/tran"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abdfnx/tran/releases/download/v0.1.0/tran_macos_v0.1.0_arm64.zip"
      sha256 "1c290882f92c27bb911fd42ddb863bdf5eadb7f72cc7bc7919f22f1e6b4bb5b5"

      def install
        bin.install "bin/tran"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/tran/releases/download/v0.1.0/tran_linux_v0.1.0_arm.zip"
      sha256 "4fc9d9d20cdce159831ec9840bf5576081edca1ea93afb6beca81798209cf4ca"

      def install
        bin.install "bin/tran"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/tran/releases/download/v0.1.0/tran_linux_v0.1.0_arm64.zip"
      sha256 "76b17aedf30d6467f6bf55a5a8776ac2157bb28dcf51ad33257c60db38f9147d"

      def install
        bin.install "bin/tran"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/tran/releases/download/v0.1.0/tran_linux_v0.1.0_amd64.zip"
      sha256 "0aaad912c42d4ffcb785e37256d18faec4280abe16fb6e868e4876f36034f78e"

      def install
        bin.install "bin/tran"
      end
    end
  end
end
