# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tran < Formula
  desc "🖥️ Securely transfer and send anything between computers with TUI"
  homepage "https://github.com/abdfnx/tran"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/abdfnx/tran/releases/download/v0.1.0/tran_macos_v0.1.0_arm64.zip"
      sha256 "84deef4d09621a906a41731611a4d08871ed03f5f6c43e0182e2f12281033134"

      def install
        bin.install "bin/tran"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/tran/releases/download/v0.1.0/tran_macos_v0.1.0_amd64.zip"
      sha256 "f0fdd0d9466820a224c8fd25c2b0db0e8fa3a3114738c421e66829f31638a65d"

      def install
        bin.install "bin/tran"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/tran/releases/download/v0.1.0/tran_linux_v0.1.0_arm64.zip"
      sha256 "8d269773857118c178365c667c46a2dd8d54fc53710d3d5a25a5faea345993ee"

      def install
        bin.install "bin/tran"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abdfnx/tran/releases/download/v0.1.0/tran_linux_v0.1.0_amd64.zip"
      sha256 "8d5b318772237b428409f90123f33dabda4cbabbbd00ca7689cfb70885516392"

      def install
        bin.install "bin/tran"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abdfnx/tran/releases/download/v0.1.0/tran_linux_v0.1.0_arm.zip"
      sha256 "49973cefb0a2c2d1403fc3e9f21cacf194ffe9855e419660f8bcfaf5827f1878"

      def install
        bin.install "bin/tran"
      end
    end
  end
end
